"""Update Parcel models

Revision ID: a9fd5fe41cf7
Revises: 6df1fe49117e
Create Date: 2024-09-23 09:45:56.149138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fd5fe41cf7'
down_revision = '6df1fe49117e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('present_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('fk_parcels_customer_id_customers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_parcels_customer_id_users'), 'users', ['customer_id'], ['id'])
        batch_op.drop_column('present_longitude')
        batch_op.drop_column('travel_distance')
        batch_op.drop_column('pickup_latitude')
        batch_op.drop_column('present_latitude')
        batch_op.drop_column('journey_duration')
        batch_op.drop_column('destination_longitude')
        batch_op.drop_column('pickup_longitude')
        batch_op.drop_column('destination_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pickup_longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('destination_longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('journey_duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('present_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pickup_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('travel_distance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('present_longitude', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_parcels_customer_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_parcels_customer_id_customers', 'customers', ['customer_id'], ['id'])
        batch_op.alter_column('present_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
